# preload = ~/.config/backgrounds/arch-rainbow-catppuccin-mocha-2.png
# wallpaper = ,~/.config/backgrounds/arch-rainbow-catppuccin-mocha-2.png

preload = ~/.config/backgrounds/raised-fist-3.png
wallpaper = ,~/.config/backgrounds/raised-fist-3.png
