
source=~/.config/hypr/configs/environment

source=~/.config/hypr/configs/mocha.conf

source=~/.config/hypr/configs/lookandfeel

source=~/.config/hypr/configs/defaults

source=~/.config/hypr/monitors.conf

source=~/.config/hypr/configs/windowrules

source=~/.config/hypr/configs/input

source=~/.config/hypr/configs/keybindings

source=~/.config/hypr/configs/permissions

source=~/.config/hypr/configs/autostart
