
source=~/.config/hypr/environment

source=~/.config/hypr/mocha.conf

source=~/.config/hypr/lookandfeel

source=~/.config/hypr/defaults

source=~/.config/hypr/monitors.conf

source=~/.config/hypr/windowrules

source=~/.config/hypr/input

source=~/.config/hypr/keybindings

source=~/.config/hypr/permissions

source=~/.config/hypr/autostart

