# preload = ~/.config/backgrounds/arch-rainbow-catppuccin-mocha-2.png
# wallpaper = ,~/.config/backgrounds/arch-rainbow-catppuccin-mocha-2.png

preload = ~/.config/backgrounds/raised-fist-3.png
# wallpaper = ,~/.config/backgrounds/raised-fist-3.png

splash = false

wallpaper {
    monitor = DP-3
    path = ~/.config/backgrounds/raised-fist-3.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/backgrounds/raised-fist-3.png
    fit_mode = cover
}

# fit_mode options: contain|cover|tile|fill
