# hyprviz configuration (created automatically)

animations {
    enabled = true
}

decoration {

    shadow {
        range = 4
    }

}

general {
    border_size = 4
    gaps_in = 3
    gaps_out = 10
}