# Preload the image(s) to make showing them instantaneous
preload = ~/.config/backgrounds/raised-fist-3.png

# No quote on wallpaper
splash = false

# Specific monitor configuration
wallpaper {
    monitor = DP-3
    path = ~/.config/backgrounds/raised-fist-3.png
    fit_mode = cover
}

# Fallback for all others
wallpaper {
    monitor = 
    path = ~/.config/backgrounds/raised-fist-3.png
    fit_mode = cover
}

# fit_mode options: contain|cover|tile|fill
# See https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/object-fit for these css modes
